In [11]:
from fastapi import FastAPI
from typing import List, Dict, Union
import pandas as pd
import pyarrow
import numpy as np 

app = FastAPI()

In [12]:
# Cargamos los DataFrames que usaremos para nuestras funciones 
games = pd.read_parquet('C:/Users/famil/OneDrive/Escritorio/Proyectos/Python_basics/PI_ML_OPS_ML/PI_ML_OPS_STEAM/Datasets/steam_games.parquet')
reviews = pd.read_parquet('C:/Users/famil/OneDrive/Escritorio/Proyectos/Python_basics/PI_ML_OPS_ML/PI_ML_OPS_STEAM/Datasets/user_reviews.parquet')
items = pd.read_parquet('C:/Users/famil/OneDrive/Escritorio/Proyectos/Python_basics/PI_ML_OPS_ML/PI_ML_OPS_STEAM/Datasets/users_items.parquet')

In [ ]:
games.head()

  genres app_name title   url release_date  tags reviews_url  id
0   None     None  None  None          NaT  None        None NaN
1   None     None  None  None          NaT  None        None NaN
2   None     None  None  None          NaT  None        None NaN
3   None     None  None  None          NaT  None        None NaN
4   None     None  None  None          NaT  None        None NaN

In [ ]:
games.dropna(subset=['id'], inplace=True)

In [ ]:
games.dtypes

genres                  object
app_name                object
title                   object
url                     object
release_date    datetime64[ns]
tags                    object
reviews_url             object
id                     float64
dtype: object

In [ ]:
reviews.dtypes

user_id                       object
user_url                      object
posted                datetime64[ns]
item_id                        int32
recommend                       bool
review                        object
sentiment_analysis             int64
dtype: object

In [ ]:
items.dtypes

user_id              object
item_id               int32
item_name            object
playtime_forever    float64
dtype: object

In [ ]:
# Unir el DataFrame games con el DataFrame items en la columna id para que nuestra funcion no sea tan pesada y sea optima en nuestra api 
df_funcion_1= pd.merge(games, items, left_on='id', right_on='item_id')
df_funcion_1

,genres,app_name,title,url,release_date,tags,reviews_url,id,user_id,item_id,item_name,playtime_forever
0,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,UTNerd24,282010,Carmageddon Max Pack,5.0
1,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,I_DID_911_JUST_SAYING,282010,Carmageddon Max Pack,0.0
2,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,76561197962104795,282010,Carmageddon Max Pack,0.0
3,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,r3ap3r78,282010,Carmageddon Max Pack,0.0
4,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,saint556,282010,Carmageddon Max Pack,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4294252,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,76561198273508956,80,Counter-Strike: Condition Zero,0.0
4294253,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,76561198282090798,80,Counter-Strike: Condition Zero,0.0
4294254,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,943525,80,Counter-Strike: Condition Zero,0.0
4294255,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,76561198283312749,80,Counter-Strike: Condition Zero,9.0
4294256,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,76561198312638244,80,Counter-Strike: Condition Zero,99.0

In [ ]:
# extraemos solo el año de la columna release_date y lo agregamos a una nueva columna 
df_funcion_1['año'] = pd.to_datetime(df_funcion_1['release_date']).dt.year
df_funcion_1.dropna(subset='año', inplace=True)
df_funcion_1['año'] = df_funcion_1['año'].astype(int)

In [ ]:
# eliminamos las columnas que nos serviran para nuestra primer funcion
df_funcion_1.drop(columns=['item_name','app_name','tags','url','release_date','reviews_url','id','item_id','user_id','title'], axis=1, inplace=True)

In [ ]:
df_funcion_1.dropna(inplace=True)
df_funcion_1

                                genres  playtime_forever   año
0        ['Action', 'Indie', 'Racing']               5.0  1997
1        ['Action', 'Indie', 'Racing']               0.0  1997
2        ['Action', 'Indie', 'Racing']               0.0  1997
3        ['Action', 'Indie', 'Racing']               0.0  1997
4        ['Action', 'Indie', 'Racing']              13.0  1997
...                                ...               ...   ...
4294252                     ['Action']               0.0  2004
4294253                     ['Action']               0.0  2004
4294254                     ['Action']               0.0  2004
4294255                     ['Action']               9.0  2004
4294256                     ['Action']              99.0  2004

[4173927 rows x 3 columns]

In [ ]:
df_funcion_1.to_parquet('PlayTimeGenre.parquet')

FUNCION 1

In [ ]:
def PlayTimeGenre(genero: str) -> Dict[str, int]:
    # Filtrar los datos por género
    df_genero = df_funcion_1[df_funcion_1['genres'].str.lower().str.contains(genero.lower())]

    if df_genero.empty:
        return {"mensaje": f"No hay datos para el género: {genero}"}

    # Dividir la columna playtime_forever para convertir el tiempo a horas ya que se encuentra en minutos
    df_genero.loc[:, 'playtime_forever'] = (df_genero['playtime_forever'] / 60).round(2)

    # Agrupar los datos por año y sumar las horas jugadas
    df_grouped = df_genero.groupby('año')['playtime_forever'].sum().reset_index()

    # Encontrar el año con más horas jugadas
    max_playtime_year = df_grouped.loc[df_grouped['playtime_forever'].idxmax(), 'año']

    return {f"Año de lanzamiento con más horas jugadas para Género {genero}": max_playtime_year}

In [ ]:
PlayTimeGenre('Action')

{'Año de lanzamiento con más horas jugadas para Género Action': 2012}

FUNCION 2

In [13]:
df_funcion_2= pd.merge(games, items, left_on='id', right_on='item_id')
df_funcion_2

,genres,app_name,title,url,release_date,tags,reviews_url,id,user_id,item_id,item_name,playtime_forever
0,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,UTNerd24,282010,Carmageddon Max Pack,5.0
1,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,I_DID_911_JUST_SAYING,282010,Carmageddon Max Pack,0.0
2,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,76561197962104795,282010,Carmageddon Max Pack,0.0
3,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,r3ap3r78,282010,Carmageddon Max Pack,0.0
4,"['Action', 'Indie', 'Racing']",None,Carmageddon Max Pack,http://store.steampowered.com/app/282010/Carma...,1997-06-30,"['Racing', 'Action', 'Classic', 'Indie', 'Gore...",http://steamcommunity.com/app/282010/reviews/?...,282010.0,saint556,282010,Carmageddon Max Pack,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4294252,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,76561198273508956,80,Counter-Strike: Condition Zero,0.0
4294253,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,76561198282090798,80,Counter-Strike: Condition Zero,0.0
4294254,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,943525,80,Counter-Strike: Condition Zero,0.0
4294255,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,76561198283312749,80,Counter-Strike: Condition Zero,9.0
4294256,['Action'],None,Counter-Strike: Condition Zero,http://store.steampowered.com/app/80/CounterSt...,2004-03-01,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'S...",http://steamcommunity.com/app/80/reviews/?brow...,80.0,76561198312638244,80,Counter-Strike: Condition Zero,99.0

In [14]:
df_funcion_2 = df_funcion_2.explode('genres')
df_funcion_2['año'] = pd.to_datetime(df_funcion_2['release_date']).dt.year
df_funcion_2.drop(columns=['tags','url','reviews_url','release_date','item_id','item_name','title','app_name','id'], axis=1,inplace=True)
df_funcion_2

,genres,user_id,playtime_forever,año
0,"['Action', 'Indie', 'Racing']",UTNerd24,5.0,1997.0
1,"['Action', 'Indie', 'Racing']",I_DID_911_JUST_SAYING,0.0,1997.0
2,"['Action', 'Indie', 'Racing']",76561197962104795,0.0,1997.0
3,"['Action', 'Indie', 'Racing']",r3ap3r78,0.0,1997.0
4,"['Action', 'Indie', 'Racing']",saint556,13.0,1997.0
...,...,...,...,...
4294252,['Action'],76561198273508956,0.0,2004.0
4294253,['Action'],76561198282090798,0.0,2004.0
4294254,['Action'],943525,0.0,2004.0
4294255,['Action'],76561198283312749,9.0,2004.0
4294256,['Action'],76561198312638244,99.0,2004.0

In [15]:
df_funcion_2 = df_funcion_2.dropna()
df_funcion_2['año'] = df_funcion_2['año'].astype(int)
df_funcion_2['genres'] = df_funcion_2['genres'].str.lower()

C:\Users\famil\AppData\Local\Temp\ipykernel_5052\2927495797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_funcion_2['año'] = df_funcion_2['año'].astype(int)
C:\Users\famil\AppData\Local\Temp\ipykernel_5052\2927495797.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_funcion_2['genres'] = df_funcion_2['genres'].str.lower()

In [16]:
df_funcion_2

,genres,user_id,playtime_forever,año
0,"['action', 'indie', 'racing']",UTNerd24,5.0,1997
1,"['action', 'indie', 'racing']",I_DID_911_JUST_SAYING,0.0,1997
2,"['action', 'indie', 'racing']",76561197962104795,0.0,1997
3,"['action', 'indie', 'racing']",r3ap3r78,0.0,1997
4,"['action', 'indie', 'racing']",saint556,13.0,1997
...,...,...,...,...
4294252,['action'],76561198273508956,0.0,2004
4294253,['action'],76561198282090798,0.0,2004
4294254,['action'],943525,0.0,2004
4294255,['action'],76561198283312749,9.0,2004
4294256,['action'],76561198312638244,99.0,2004

In [17]:
df_funcion_2['playtime_forever']= (df_funcion_2['playtime_forever'] /60)
df_funcion_2

C:\Users\famil\AppData\Local\Temp\ipykernel_5052\187811731.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_funcion_2['playtime_forever']= (df_funcion_2['playtime_forever'] /60)

,genres,user_id,playtime_forever,año
0,"['action', 'indie', 'racing']",UTNerd24,0.083333,1997
1,"['action', 'indie', 'racing']",I_DID_911_JUST_SAYING,0.000000,1997
2,"['action', 'indie', 'racing']",76561197962104795,0.000000,1997
3,"['action', 'indie', 'racing']",r3ap3r78,0.000000,1997
4,"['action', 'indie', 'racing']",saint556,0.216667,1997
...,...,...,...,...
4294252,['action'],76561198273508956,0.000000,2004
4294253,['action'],76561198282090798,0.000000,2004
4294254,['action'],943525,0.000000,2004
4294255,['action'],76561198283312749,0.150000,2004
4294256,['action'],76561198312638244,1.650000,2004

In [18]:
df_funcion_2 = df_funcion_2.sample(frac=0.010)
df_funcion_2

,genres,user_id,playtime_forever,año
493408,['action'],76561198070549039,0.483333,2011
3932991,['strategy'],Donato_Dyas,0.716667,2009
12569,"['action', 'indie', 'rpg']",b0ing,0.566667,2006
3930460,['strategy'],76561198046962057,0.833333,2009
3712833,['strategy'],76561198066959946,37.400000,2010
...,...,...,...,...
361437,['action'],gristy,0.500000,2010
36237,"['indie', 'simulation']",76561198047166475,47.966667,2006
345462,['rpg'],Unl33t,2.566667,2009
821279,"['adventure', 'indie']",76561198074104657,0.000000,2012
551280,"['action', 'casual', 'indie', 'strategy']",NeoGhostExcalibur,1.233333,2011

In [19]:
df_funcion_2.to_parquet('UserForGenre.parquet')

In [9]:
def UserForGenre(genero: str) -> Dict[str, Union[str, List[Dict[str, float]]]]:
    # Filtrar los datos por género
    df_genero = df_funcion_2[df_funcion_2['genres'].str.contains(genero.lower(), na=False)]

    if df_genero.empty:
        return {"mensaje": f"No hay datos para el género: {genero}"}

    # Agrupar los datos por usuario y año
    df_grouped = df_genero.groupby(['user_id', 'año']).agg({'playtime_forever': 'sum'}).reset_index()

    # Encontrar el usuario con más horas jugadas
    max_playtime_user = df_grouped.loc[df_grouped['playtime_forever'].idxmax(), 'user_id']

    # Crear una lista de la acumulación de horas jugadas por año para ese usuario
    user_data = df_grouped[df_grouped['user_id'] == max_playtime_user]
    user_data = user_data.rename(columns={'playtime_forever': 'Horas'})
    horas_jugadas = user_data[['año', 'Horas']].to_dict('records')

    return {"Usuario con más horas jugadas para el género proporcionado es": max_playtime_user, "Horas jugadas": horas_jugadas}

In [10]:
UserForGenre('indie')

{'Usuario con más horas jugadas para el género proporcionado es': 'REBAS_AS_F-T',
 'Horas jugadas': [{'año': 1999, 'Horas': 0.0},
  {'año': 2001, 'Horas': 0.18333333333333332},
  {'año': 2003, 'Horas': 31.05},
  {'año': 2005, 'Horas': 0.0},
  {'año': 2006, 'Horas': 27.883333333333333},
  {'año': 2007, 'Horas': 17.833333333333332},
  {'año': 2008, 'Horas': 22.766666666666666},
  {'año': 2009, 'Horas': 483.2166666666667},
  {'año': 2010, 'Horas': 358.1166666666667},
  {'año': 2011, 'Horas': 1669.25},
  {'año': 2012, 'Horas': 2474.3166666666666},
  {'año': 2013, 'Horas': 2822.4833333333336},
  {'año': 2014, 'Horas': 5448.783333333333},
  {'año': 2015, 'Horas': 12529.416666666666},
  {'año': 2016, 'Horas': 13572.883333333333},
  {'año': 2017, 'Horas': 564.7833333333333}]}

FUNCION 3

In [3]:
df_funcion_3_y_4 = pd.merge(reviews,games,left_on='item_id',right_on='id')
df_funcion_3_y_4

,user_id,user_url,posted,item_id,recommend,review,sentiment_analysis,genres,app_name,title,url,release_date,tags,reviews_url,id
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,2011-11-05,1250,True,Simple yet with great replayability. In my opi...,2,['Action'],None,Killing Floor,http://store.steampowered.com/app/1250/Killing...,2009-05-14,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",http://steamcommunity.com/app/1250/reviews/?br...,1250.0
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,2011-07-15,22200,True,It's unique and worth a playthrough.,2,"['Action', 'Indie']",None,Zeno Clash,http://store.steampowered.com/app/22200/Zeno_C...,2009-04-21,"['Action', 'Indie', 'Surreal', ""Beat 'em up"", ...",http://steamcommunity.com/app/22200/reviews/?b...,22200.0
2,js41637,http://steamcommunity.com/id/js41637,2013-09-08,227300,True,For a simple (it's actually not all that simpl...,2,"['Indie', 'Simulation']",None,Euro Truck Simulator 2,http://store.steampowered.com/app/227300/Euro_...,2013-01-16,"['Simulation', 'Driving', 'Open World', 'Reali...",http://steamcommunity.com/app/227300/reviews/?...,227300.0
3,js41637,http://steamcommunity.com/id/js41637,2013-11-29,239030,True,Very fun little game to play when your bored o...,2,"['Adventure', 'Indie']",None,"Papers, Please",http://store.steampowered.com/app/239030/Paper...,2013-08-08,"['Indie', 'Political', 'Simulation', 'Point & ...",http://steamcommunity.com/app/239030/reviews/?...,239030.0
4,evcentric,http://steamcommunity.com/id/evcentric,NaT,248820,True,A suitably punishing roguelike platformer. Wi...,2,"['Action', 'Indie', 'RPG']",None,Risk of Rain,http://store.steampowered.com/app/248820/Risk_...,2013-11-08,"['Rogue-like', 'Indie', 'Platformer', 'Action'...",http://steamcommunity.com/app/248820/reviews/?...,248820.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53983,Fuckfhaisjnsnsjakaka,http://steamcommunity.com/id/Fuckfhaisjnsnsjakaka,NaT,70,True,a must have classic from steam definitely wort...,2,['Action'],None,Half-Life,http://store.steampowered.com/app/70/HalfLife/,1998-11-08,"['FPS', 'Classic', 'Action', 'Sci-fi', 'Single...",http://steamcommunity.com/app/70/reviews/?brow...,70.0
53984,3214213216,http://steamcommunity.com/id/3214213216,NaT,362890,True,this game is a perfect remake of the original ...,2,"['Action', 'Adventure', 'Indie', 'Early Access']",None,Black Mesa,http://store.steampowered.com/app/362890/Black...,2015-05-05,"['Early Access', 'FPS', 'Remake', 'Action', 'S...",http://steamcommunity.com/app/362890/reviews/?...,362890.0
53985,ChrisCoroner,http://steamcommunity.com/id/ChrisCoroner,NaT,273110,True,had so much fun plaing this and collecting res...,2,"['Action', 'Casual', 'Free to Play', 'Massivel...",None,Counter-Strike Nexon: Zombies,http://store.steampowered.com/app/273110/Count...,2014-10-07,"['Free to Play', 'Zombies', 'Multiplayer', 'FP...",http://steamcommunity.com/app/273110/reviews/?...,273110.0
53986,CaptainAmericaCw,http://steamcommunity.com/id/CaptainAmericaCw,NaT,730,True,:D,2,['Action'],None,Counter-Strike: Global Offensive,http://store.steampowered.com/app/730/CounterS...,2012-08-21,"['FPS', 'Multiplayer', 'Shooter', 'Action', 'T...",http://steamcommunity.com/app/730/reviews/?bro...,730.0
53987,76561198267374962,http://steamcommunity.com/profiles/76561198267...,NaT,440,True,so much fun :D,2,"['Action', 'Free to Play']",None,Team Fortress 2,http://store.steampowered.com/app/440/Team_For...,2007-10-10,"['Free to Play', 'Multiplayer', 'FPS', 'Action...",http://steamcommunity.com/app/440/reviews/?bro...,440.0

In [4]:
df_funcion_3_y_4.drop(columns=['posted','user_url','review','item_id','genres','url','tags','reviews_url','id','app_name'],axis=1,inplace=True)
df_funcion_3_y_4

,user_id,recommend,sentiment_analysis,title,release_date
0,76561197970982479,True,2,Killing Floor,2009-05-14
1,76561197970982479,True,2,Zeno Clash,2009-04-21
2,js41637,True,2,Euro Truck Simulator 2,2013-01-16
3,js41637,True,2,"Papers, Please",2013-08-08
4,evcentric,True,2,Risk of Rain,2013-11-08
...,...,...,...,...,...
53983,Fuckfhaisjnsnsjakaka,True,2,Half-Life,1998-11-08
53984,3214213216,True,2,Black Mesa,2015-05-05
53985,ChrisCoroner,True,2,Counter-Strike Nexon: Zombies,2014-10-07
53986,CaptainAmericaCw,True,2,Counter-Strike: Global Offensive,2012-08-21
53987,76561198267374962,True,2,Team Fortress 2,2007-10-10

In [5]:
df_funcion_3y_4 = df_funcion_3_y_4.dropna()
df_funcion_3_y_4

,user_id,recommend,sentiment_analysis,title,release_date
0,76561197970982479,True,2,Killing Floor,2009-05-14
1,76561197970982479,True,2,Zeno Clash,2009-04-21
2,js41637,True,2,Euro Truck Simulator 2,2013-01-16
3,js41637,True,2,"Papers, Please",2013-08-08
4,evcentric,True,2,Risk of Rain,2013-11-08
...,...,...,...,...,...
53983,Fuckfhaisjnsnsjakaka,True,2,Half-Life,1998-11-08
53984,3214213216,True,2,Black Mesa,2015-05-05
53985,ChrisCoroner,True,2,Counter-Strike Nexon: Zombies,2014-10-07
53986,CaptainAmericaCw,True,2,Counter-Strike: Global Offensive,2012-08-21
53987,76561198267374962,True,2,Team Fortress 2,2007-10-10

In [6]:
df_funcion_3_y_4['anio'] = pd.to_datetime(df_funcion_3_y_4['release_date']).dt.year
df_funcion_3_y_4.dropna(subset=['anio'],inplace=True)
df_funcion_3_y_4['anio'] = df_funcion_3_y_4['anio'].astype(int)
df_funcion_3_y_4

,user_id,recommend,sentiment_analysis,title,release_date,anio
0,76561197970982479,True,2,Killing Floor,2009-05-14,2009
1,76561197970982479,True,2,Zeno Clash,2009-04-21,2009
2,js41637,True,2,Euro Truck Simulator 2,2013-01-16,2013
3,js41637,True,2,"Papers, Please",2013-08-08,2013
4,evcentric,True,2,Risk of Rain,2013-11-08,2013
...,...,...,...,...,...,...
53983,Fuckfhaisjnsnsjakaka,True,2,Half-Life,1998-11-08,1998
53984,3214213216,True,2,Black Mesa,2015-05-05,2015
53985,ChrisCoroner,True,2,Counter-Strike Nexon: Zombies,2014-10-07,2014
53986,CaptainAmericaCw,True,2,Counter-Strike: Global Offensive,2012-08-21,2012
53987,76561198267374962,True,2,Team Fortress 2,2007-10-10,2007

In [7]:
df_funcion_3_y_4.drop(columns=['release_date'],inplace=True)
df_funcion_3_y_4

,user_id,recommend,sentiment_analysis,title,anio
0,76561197970982479,True,2,Killing Floor,2009
1,76561197970982479,True,2,Zeno Clash,2009
2,js41637,True,2,Euro Truck Simulator 2,2013
3,js41637,True,2,"Papers, Please",2013
4,evcentric,True,2,Risk of Rain,2013
...,...,...,...,...,...
53983,Fuckfhaisjnsnsjakaka,True,2,Half-Life,1998
53984,3214213216,True,2,Black Mesa,2015
53985,ChrisCoroner,True,2,Counter-Strike Nexon: Zombies,2014
53986,CaptainAmericaCw,True,2,Counter-Strike: Global Offensive,2012
53987,76561198267374962,True,2,Team Fortress 2,2007

In [8]:
df_funcion_3_y_4.to_parquet('UsersR.parquet')

In [21]:
@app.get("/UsersRecommend/{año}")
def UsersRecommend(año: int) -> List[Dict[str, str]]:
    # Filtrar las reseñas que son recomendaciones y tienen un análisis de sentimiento positivo o neutral
    filtro = df_funcion_3_y_4[(df_funcion_3_y_4['recommend'] == True) & (df_funcion_3_y_4['sentiment_analysis'].isin([1, 2]))]

    # Filtrar los juegos que se lanzaron en el año dado
    filtro = filtro[filtro['anio'] == año]

    # Contar las recomendaciones para cada juego
    cuenta_de_recomendaciones = filtro['title'].value_counts()

    # Obtener los tres juegos con más recomendaciones, si hay al menos tres juegos
    if len(cuenta_de_recomendaciones) >= 3:
        top_juegos = cuenta_de_recomendaciones.nlargest(3).index.tolist()
        return [{"Puesto 1": top_juegos[0]}, {"Puesto 2": top_juegos[1]}, {"Puesto 3": top_juegos[2]}]
    else:
        return [{"mensaje": "No hay suficientes juegos con recomendaciones para el año dado."}]

In [22]:
UsersRecommend(2010)

[{'Puesto 1': "Sid Meier's Civilization® V"},
 {'Puesto 2': 'Mount &amp; Blade: Warband'},
 {'Puesto 3': 'Fallout: New Vegas'}]

FUNCION 4

In [23]:
@app.get("/UsersNotRecommend/{año}")
def UsersNotRecommend(año: int) -> List[Dict[str, str]]:
    # Filtrar las reseñas que son recomendaciones y tienen un análisis de sentimiento positivo o neutral
    filtrado = df_funcion_3_y_4[(df_funcion_3_y_4['recommend'] == False) & (df_funcion_3_y_4['sentiment_analysis'].isin([0]))]

    # Filtrar los juegos que se lanzaron en el año dado
    filtrado = filtrado[filtrado['anio'] == año]

    # Contar las recomendaciones para cada juego
    cuenta_negativa = filtrado['title'].value_counts()

    # Devolver los tres juegos con más recomendaciones
    top_juegos_norecomendados = cuenta_negativa.nlargest(3).index.tolist()

    return [{"Puesto 1": top_juegos_norecomendados[0]}, {"Puesto 2": top_juegos_norecomendados[1]}, {"Puesto 3": top_juegos_norecomendados[2]}]

In [24]:
UsersNotRecommend(2010)

[{'Puesto 1': "Sid Meier's Civilization® V"},
 {'Puesto 2': 'Quake Live™'},
 {'Puesto 3': "Assassin's Creed 2 Deluxe Edition"}]

FUNCION 5

In [26]:
@app.get("/sentiment_analysis/{año}")
def sentiment_analysis(año: int) -> Dict[str, int]:
    #filtramos el dataframe por año 
    df_filtrado = df_funcion_3_y_4[df_funcion_3_y_4['anio'] == año]

    # Contar la cantidad de registros de reseñas que se encuentren categorizados con un análisis de sentimiento
    contar_sentimientos = df_filtrado['sentiment_analysis'].value_counts()
        # Crear un nuevo diccionario con el formato deseado
    salida_deseada = {
        f"En el año {año} hubo comentarios": {
            "positivos": contar_sentimientos.get(2, 0),
            "neutrales": contar_sentimientos.get(1, 0),
            "negativos": contar_sentimientos.get(0, 0)
        }
    }

    return salida_deseada

In [27]:
sentiment_analysis(2012)

{'En el año 2012 hubo comentarios': {'positivos': 5678,
  'neutrales': 1951,
  'negativos': 1426}}

In [28]:
df_funcion_1.info()

NameError: name 'df_funcion_1' is not defined

In [29]:
df_funcion_3_y_4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50354 entries, 0 to 53987
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   recommend           50354 non-null  bool
 1   sentiment_analysis  50354 non-null  int64
 2   title               50354 non-null  object
 3   anio                50354 non-null  int32
dtypes: bool(1), int32(1), int64(1), object(1)
memory usage: 1.4+ MB